### ISSUE TITLE
Is there an example repo?

### ISSUE THREAD

**Issue by lucifer1004** [pranaygp/mdx-code#2]
I ran into webpack issue when trying to import mdx-code into mdx-deck.

mdx-deck is currently using Babel 6, while this project seems to require Babel 7.

I cannot figure out the exact reason.

**Comment by pranaygp** [comment]
Here's an example repo: https://github.com/pranaygp/granular-slides

**Comment by pranaygp** [comment]
`babel` is only a dev-dependency here. The version published to npm is precompiled with babel so you shouldn't be running into any such issue

**Comment by lucifer1004** [comment]
Here is my repo: https://github.com/pkuosa-gabriel/mdx-deck-example/tree/mdx-code

Now deployment failed with 

> 
webpack:///./node_modules/mdx-deck/dist/entry.js?:1
throw new Error("Module build failed (from ./node_modules/babel-loader/lib/index.js):\nError: Requires Babel \"^7.0.0-0\", but was loaded with \"6.26.3\". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention \"@babel/core\" or \"babel-core\" to see what is calling Babel.\n    at throwVersionError (/tmp/439b41ba/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)\n    at Object.assertVersion (/tmp/439b41ba/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)\n    at api (/tmp/439b41ba/node_modules/@babel/plugin-syntax-jsx/lib/index.js:19:7)\n    at /tmp/439b41ba/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12\n    at Function.memoisePluginContainer (/tmp/439b41ba/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)\n    at Functio

Would you please have a look at my code? I'd really appreciate that!

**Comment by pranaygp** [comment]
Your code seems alright. I've been struggling with deploying any `mdx-deck` project with Now myself and it seems like it's an issue on their end (they seem to be installing the devDependencies recursively 🤔). You should follow up with ZEIT on this issue

**Comment by lucifer1004** [comment]
Thanks a lot.
